# Generated by Django 4.2.16 on 2025-06-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("calendarapp", "0023_remove_event_day_remove_event_nurse_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SanitationTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarapp.globalobject",
                    ),
                ),
                (
                    "nurse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanitation_tasks",
                        to="calendarapp.nurse",
                    ),
                ),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
    ]
