# Generated by Django 4.2.16 on 2025-06-26 23:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0025_clockentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockentry',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendarapp.nurse'),
        ),
        migrations.AlterField(
            model_name='clockentry',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
