# Generated by Django 4.2.16 on 2025-07-01 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0026_alter_clockentry_nurse_alter_clockentry_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursedayshifttype',
            name='GlobalObject',
            field=models.ForeignKey(default=115, on_delete=django.db.models.deletion.CASCADE, to='calendarapp.globalobject'),
            preserve_default=False,
        ),
    ]
