# Generated by Django 4.2.16 on 2025-07-01 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0028_nursedayshifttype_x'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursedayshifttype',
            name='x',
        ),
    ]
