# Generated by Django 4.2.16 on 2025-07-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0029_remove_nursedayshifttype_x'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursedayshifttype',
            old_name='GlobalObject',
            new_name='GlobalObject_id',
        ),
    ]
