# Generated by Django 4.2.16 on 2025-07-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0030_rename_globalobject_nursedayshifttype_globalobject_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nursedayshifttype',
            old_name='GlobalObject_id',
            new_name='GlobalObject',
        ),
    ]
