# Generated by Django 4.2.16 on 2025-07-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0031_rename_globalobject_id_nursedayshifttype_globalobject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursedayshifttype',
            name='GlobalObject',
        ),
    ]
